function cellInfo = monoDetectorTunable(varargin) 
% MONODETECTORTUNABLE returns a cell array containing bus object information 
% 
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject 
%                 when the MATLAB file is executed. 
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode, DimensionsMode, Min, Max, DocUnits, Description 

suppressObject = false; 
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false 
    suppressObject = true; 
elseif nargin > 1 
    error('Invalid input argument(s) encountered'); 
end 

cellInfo = { ... 
  { ... 
    'MonoDetectorTunable', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', {... 
{'levelPole', 1, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'levelGain', 1, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'lsSmoothPole', 1, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'lsSmoothGain', 1, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'lsSmoothResetPole', 1, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'lsSmoothResetGain', 1, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'leftRightMatchTolerance', 1, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'thresholdZeroLevel', 1, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'thresholdMono', 1, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'thresholdStereo', 1, 'single', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
}'; 

if ~suppressObject 
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo) 
end 
